# Generated by Django 4.2.11 on 2024-03-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('no_of_questions', models.IntegerField()),
                ('time', models.IntegerField(help_text='quiz duration in minutes')),
                ('pass_mark', models.IntegerField(help_text='pass score in %')),
                ('difficulty', models.CharField(choices=[('hard', 'hard'), ('medium', 'medium'), ('easy', 'easy')], max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Quizes',
            },
        ),
    ]
